version: 2

updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "monthly"
    target-branch: "dev"
    # Apply only major or minor updates, ignore patches
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]
    # Add reviewers
    reviewers:
      - "albertmeronyo"
      - "c-martinez"
