; SPDX-FileCopyrightText: 2022 Albert Meroño, Rinke Hoekstra, Carlos Martínez
;
; SPDX-License-Identifier: MIT

[auth]
github_access_token = xxx
gitlab_access_token = yyy

[local]
local_sparql_dir = /home/grlc/queries/

[defaults]
# Default endpoint, if none specified elsewhere
sparql_endpoint = http://dbpedia.org/sparql
server_name = grlc.io

# endpoint default authentication
user = none
password = none
# sparql_access_token = SPARQL endpoint HTTP authorization token

# Logging level
debug = True

[api_gitlab]
gitlab_url=https://gitlab.com

[user_agent]
# User agent information
# Results in User-Agent: <product>/<version> (<comment>)
# e.g. User-Agent: grlc/1.3.11 (https://github.com/CLARIAH/grlc)
product = grlc
version = 1.3.11
comment = https://github.com/CLARIAH/grlc